### ISSUE TITLE
Support standard XCompose files?

### ISSUE THREAD

**Issue by dcherian** [Granitosaurus/macos-compose#1]
This is an awesome project. Thank you!

I have been using XCompose on linux with the files here (https://github.com/kragen/xcompose) for a long time and it's been quite annoying to not have this on Mac.

Would it be possible to make `gen-compose` work with "standard" compose files already in use? The syntax looks like this

```
<Multi_key> <minus> <less>		: "←"	leftarrow	# LEFTWARDS ARROW
```

**Comment by Granitosaurus** [comment]
Yeah I've been writing a converter already! So it's WIP :)
Thats a really good repo for testing!

**Comment by Granitosaurus** [comment]
I've added initial support via https://github.com/Granitosaurus/macos-compose/pull/2 

Still need tests and I'm experimenting whether mac's key map can support special characters such as arrows as some xcompose maps have those and right now they are just ignored.

**Comment by dcherian** [comment]
thanks! I'll try it out soon.

**Comment by Granitosaurus** [comment]
Implemented via https://github.com/Granitosaurus/macos-compose/pull/2
